### ISSUE TITLE
Created a component to step through and complete today's scheduled workout routine

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/workout-app#14]
# User story:
As a user, I want to be able to see my scheduled workouts for the day and track my progress toward my fitness goals.

## Acceptance criteria:
- When I log in to the application, I should be able to see my scheduled workouts for the day displayed in a progress tracker.
- The routine tracker should show each workout as a step and indicate which workouts have already been completed.
- I should be able to mark each workout as completed by submitting a workout round.
- If a workout has already been completed prior to opening the progress tracker, it should be automatically marked as completed.
- It should update in real-time to reflect which workouts have been completed.
- Upon completion of a workout routine, a table should display each completed round with summary metrics. The table should also allow the user to remove rounds and this will update the routine tracker.
- The routine tracker should include UI elements such as charts and tables to provide additional information about my progress.

## Related Issues:
- #13: Dashboard Page
- #15

## Task:
- [x] Redux state management 
- [x] Routes and controllers
- [x] Full Component Life Cycle
- [x] Conditional Rendering
- [x] Workouts summary table component
- [x] Progress Chart Component

## Design:

![Image](https://user-images.githubusercontent.com/65479004/221385994-e26e4eb5-2303-4344-8b87-5a535b4ca0ec.png)

**Comment by JaredMabus** [comment]
close: 90654cab4a643140642d5ba5455fbe605b05590a
