### ISSUE TITLE
Create a responsive StepLine chart component for tracking workout progress

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/workout-app#15]
# User Story:

As a fitness enthusiast, I want to see the progress of my workout performance over time using a StepLine chart, so that I can track my progress and adjust my workout routine accordingly.

## Acceptance Criteria:

- The component must accept a prop "data" which is an object that contains the details of a workout or an empty array if there's no data available.
- The component must display the name of the workout and "No Data" if the workout object is empty or null.
- Will convert the workout object's data into a StepLine chart data format with 3 lines representing the "Weight", "Reps", and "Sets" data points respectively.
- it will be responsive and adjust its size based on the available space.

# Task
- [x]  Setup `nivo` (Javascript data visualization library)
- [x] Mock design and prototype component
- [x] Component container 
- [x] State and Redux functionality
  - [x] Create a filter state object for filtering options
  - [x] Filter based on 'active method' from the workouts card

# Design:

![Image](https://user-images.githubusercontent.com/65479004/221385994-e26e4eb5-2303-4344-8b87-5a535b4ca0ec.png)

**Comment by JaredMabus** [comment]
close #504f1e4
