### ISSUE TITLE
Deploy MVP on AWS

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/workout-app#17]
# Task

## 1. Prepare code for production environment
- [x]   Optimize Express
- [x]   Use environment variables for sensitive data
- [x]   Implement pm2 clustering for scalability
- [x]   Test build script commands

## 2. Docker Container
- [x]   Create a Dockerfile 
- [x]   Test local Docker env
- [x]   Create dev and prod `docker-compose.yml`
  - [x]   Set up a volume to persist data between container and host for dev env
  - [x]   Set env variables

## 3. Set up a production server
- [x]   Set up EC2 instance
- [x]   Install and configure NGINX as a reverse proxy server (either through docker or manual install)

## 4. Deployment & CI/CD on AWS
- [x] Configure ECR  
- [x] Configure CodePipeline
  - [x] CodeBuild
- [ ] Configure ECS
  - [x] Service
  - [x] Task
  - [ ] Network
