### ISSUE TITLE
Server Setup

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/workout-app#3]
# Purpose
Create and configure node express server

# Task

- [x] Models
- [x] APIs
- [x] Controllers
- [x] Seeds

## Express Setup Task
- [x] Mongoose connection
- [x] morgan dev logging
- [x] json urlencoding middleware
- [x] static file route

**Comment by JaredMabus** [comment]
closed: #6
